// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRNavigationService.FindHandlersInProjectOptimized(Microsoft.CodeAnalysis.Compilation,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{VSIXExtention.MediatRPatternMatcher.MediatRHandlerInfo}}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRNavigationService.FindHandlersOptimized(Microsoft.CodeAnalysis.Solution,VSIXExtention.MediatRPatternMatcher.MediatRRequestInfo)~System.Threading.Tasks.Task{System.Collections.Generic.List{VSIXExtention.MediatRPatternMatcher.MediatRHandlerInfo}}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRNavigationService.FindHandlersWithCaching(Microsoft.CodeAnalysis.Solution,VSIXExtention.MediatRPatternMatcher.MediatRRequestInfo)~System.Threading.Tasks.Task{System.Collections.Generic.List{VSIXExtention.MediatRPatternMatcher.MediatRHandlerInfo}}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRNavigationService.FindNotificationHandlersInProjectOptimized(Microsoft.CodeAnalysis.Compilation,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{VSIXExtention.MediatRPatternMatcher.MediatRHandlerInfo}}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRNavigationService.NavigateToHandlers(System.Collections.Generic.List{VSIXExtention.MediatRPatternMatcher.MediatRHandlerInfo},System.Boolean)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRNavigationService.NavigateToPosition(Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame,Microsoft.CodeAnalysis.Text.LinePosition)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRNavigationService.OpenDocumentAndNavigate(System.String,Microsoft.CodeAnalysis.Text.LinePosition)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRNavigationService.ProcessSyntaxTreeForHandlers(Microsoft.CodeAnalysis.Compilation,Microsoft.CodeAnalysis.SyntaxTree,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Collections.Generic.List{VSIXExtention.MediatRPatternMatcher.MediatRHandlerInfo}}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRPatternMatcher.FindHandlersInProject(Microsoft.CodeAnalysis.Compilation,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{VSIXExtention.MediatRPatternMatcher.MediatRHandlerInfo}}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRPatternMatcher.FindHandlersInSolution(Microsoft.CodeAnalysis.Solution,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{VSIXExtention.MediatRPatternMatcher.MediatRHandlerInfo}}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRPatternMatcher.FindNotificationHandlersInProject(Microsoft.CodeAnalysis.Compilation,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{VSIXExtention.MediatRPatternMatcher.MediatRHandlerInfo}}")]
[assembly: SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:VSIXExtention.MediatRPatternMatcher.FindNotificationHandlersInSolution(Microsoft.CodeAnalysis.Solution,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{VSIXExtention.MediatRPatternMatcher.MediatRHandlerInfo}}")]
